# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CodeStrux Tech
author:
  name: Codestrux Tech
  email: contact@codestrux.tech
description: >- # this means to ignore newlines until "baseurl:"
  Codestrux Tech is a leading software development company based in Costa Rica,
  specializing in scalable cloud applications, API integrations, software
  containerization, and high availability solutions. We deliver robust,
  enterprise-grade software that drives business growth.
show_excerpts: false # set to true to show excerpts on the homepage
heading: Building Scalable Solutions for Modern Businesses
subheading: >
  At Codestrux Tech, we offer comprehensive software development services designed to meet the evolving needs of modern businesses. Our expertise spans across cloud technologies, system integration, containerization, and high availability architectures.


# Build settings
# aao: theme: minima
theme: jekyll-nord-theme
plugins:
  - jekyll-feed

jekyll-nord-theme:
  date_format: "%Y-%b-%d"

  # generate social links in footer
  social_links:
    twitter: codestrux
    github:  CodeStrux
    linkedin: alvaroaraya
